spring:
  application:
    name: mongo-test

  data:
    mongodb:
      uri: mongodb://test_user:test_pass@localhost:27017/test_spring


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true


